title: FEDRamp Controls Explorer

page_gen-dirs: false # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'controls'
    template: 'control'
    name: 'TITLE'
    dir: 'controls'

  - data: 'enhancements'
    template: 'enhancement'
    name: 'ID'
    dir: 'enhancements'


sass:
  sass_dir: css
