title: FEDRamp Controls Explorer

page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'controls'
    template: 'control'
    name: 'TITLE'
    dir: 'controls'


sass:
  sass_dir: css
