title: FEDRamp Controls Explorer

page_gen-dirs: false # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'controls'
    template: 'control'
    name: 'ID'
    dir: 'controls'

  - data: 'enhancements'
    template: 'enhancement'
    name: 'ID'
    dir: 'enhancements'

algolia:
  application_id: 'TEMKLFF1N6'
  index_name: fedramp_search
  max_record_size: 10_000
  extensions_to_index:
    - html  


sass:
  sass_dir: css
